[package]
name = "grey"
version = "0.1.0"
edition = "2021"
description = "A lightweight tool for checking the health of online services and reporting this to a monitoring system."

[[bin]]
name = "grey"
path = "./src/main.rs"

[dependencies]
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
lazy_static = "1.4"
openssl-sys = { version = "0.9", features=["vendored"], optional = true }
opentelemetry = { version = "0.22" }
opentelemetry-otlp = { version = "0.15", features = ["tls-roots"] }
opentelemetry_sdk = { version = "0.22", features = ["rt-tokio"] }
rand = "0.8"
reqwest = { version = "0.12", features = ["rustls-tls-webpki-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["fs", "macros", "net", "rt", "time", "tracing"] }
tonic = { version = "0.11", features = ["tls-roots"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-attributes = { git="https://github.com/SierraSoftworks/tracing.git" }
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
tracing-opentelemetry = "0.23"
tracing-subscriber = { version = "0.3.18", features = ["tracing-log"] }
trust-dns-resolver = { version = "0.23", features = ["tokio-runtime"] }

[features]
default = []
pure_tests = []
openssl_src = ["dep:openssl-sys"]

[profile.release]
debug = "limited"