[package]
name = "grey-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = { version = "1.0" }
humantime-serde = "1.1.1"

[features]
default = []
