[package]
name = "grey-api"
edition = "2024"
version.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
serde.workspace = true
chrono.workspace = true
humantime-serde.workspace = true

[dev-dependencies]
rmp-serde.workspace = true