name: "Nix"
on:
  pull_request:
  push:
jobs:
  flake:
    name: "Flake"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v15
      with:
        name: sierrasoftworks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix build .#
    - run: nix flake check